[package]
name = "rust-hello-world"
repository = "https://github.com/jeasai/rust-hello-world.git"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
